# Generated by Django 4.1 on 2024-08-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fototgrafia',
            new_name='Fotografia',
        ),
    ]
